apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "incidentdesk.fullname" . }}-config
  labels:
    {{- include "incidentdesk.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  DB_HOST: {{ include "incidentdesk.dbHost" . | quote }}
  DB_NAME: {{ .Values.postgres.database | quote }}
  DB_USER: {{ .Values.postgres.username | quote }}
