#!/bin/bash
run() { echo "\$ $*"; eval "$@" 2>&1 | head -25; echo; }
sec() { echo; echo "==================================================="; echo "  $*"; echo "==================================================="; }

rm -rf /root/cheat; mkdir -p /root/cheat; cd /root/cheat

sec "1. WHERE AM I / WHO AM I  (orientation)"
run "pwd"
run "whoami"
run "id"
run "hostname"
run "hostnamectl --no-pager"
run "uname -a"
run "uptime"
run "date"
run "cal 2>/dev/null || date '+%B %Y'"

sec "2. NAVIGATION  (cd, ls, tree)"
run "mkdir -p project/{src,docs,tests}"
run "ls"
run "ls -l"
run "ls -la"
run "ls -lh"
run "ls -lt"
run "ls -R"
run "tree project"
run "cd project/src && pwd && cd - && pwd"

sec "3. CREATING FILES & DIRECTORIES  (touch, mkdir, cp, mv, rm)"
run "touch project/src/app.py project/src/utils.py"
run "mkdir -p deep/nested/path"
run "ls -l project/src"
run "cp project/src/app.py project/src/app.py.bak"
run "cp -r project backup_project"
run "mv project/src/utils.py project/src/helpers.py"
run "ls -l project/src"
run "rm project/src/app.py.bak"
run "rm -rf deep"
run "ls"

sec "4. VIEWING FILE CONTENT  (cat, less, head, tail, wc)"
run "printf 'line1\nline2\nline3\nline4\nline5\nline6\nline7\nline8\nline9\nline10\n' > numbers.txt"
run "cat numbers.txt"
run "cat -n numbers.txt"
run "head -3 numbers.txt"
run "tail -3 numbers.txt"
run "wc -l numbers.txt"
run "wc numbers.txt"
echo "-- less / more open an interactive pager (q to quit) --"
echo "-- tail -f follows a file live, e.g. tail -f /var/log/syslog --"

sec "5. SEARCHING  (grep, find, locate, which)"
run "grep 'line5' numbers.txt"
run "grep -n 'line' numbers.txt | head -4"
run "grep -c 'line' numbers.txt"
run "grep -i 'LINE1' numbers.txt"
run "grep -v 'line1' numbers.txt | head -3"
run "grep -r 'line5' ."
run "find . -name '*.py'"
run "find . -type d"
run "find . -type f -size +0c | head -5"
run "find /etc -name 'passwd' 2>/dev/null"
run "which bash grep"
run "type cd"

sec "6. TEXT PROCESSING  (cut, sort, uniq, awk, sed, tr)"
run "printf 'banana,3\napple,5\ncherry,1\napple,5\n' > fruit.csv"
run "cat fruit.csv"
run "cut -d, -f1 fruit.csv"
run "sort fruit.csv"
run "sort -u fruit.csv"
run "uniq -c fruit.csv"
run "awk -F, '{print \$1 \" costs \" \$2}' fruit.csv"
run "sed 's/apple/AVOCADO/g' fruit.csv"
run "cat numbers.txt | tr 'a-z' 'A-Z' | head -3"
run "head -3 /etc/passwd | cut -d: -f1,7"

sec "7. PERMISSIONS & OWNERSHIP  (chmod, chown, umask)"
run "touch script.sh"
run "ls -l script.sh"
run "chmod +x script.sh"
run "ls -l script.sh"
run "chmod 644 script.sh"
run "ls -l script.sh"
run "chmod 755 script.sh"
run "ls -l script.sh"
echo "-- rwx = 4+2+1 ; 755 = rwxr-xr-x (owner all, group+other read/execute) --"
run "chown testuser:testuser script.sh"
run "ls -l script.sh"
run "umask"
run "stat -c '%A %a %U %G %n' script.sh"

sec "8. PROCESSES  (ps, top, kill, jobs)"
run "ps"
run "ps aux | head -8"
run "ps -ef | head -6"
run "ps -eo pid,ppid,user,%cpu,%mem,comm --sort=-%cpu | head -8"
run "pgrep -a nginx"
run "pstree -p 2>/dev/null | head -10 || echo 'pstree not installed'"
echo "-- top / htop are the interactive live process monitors --"
echo "\$ sleep 300 &   # start a background job"
sleep 300 >/dev/null 2>&1 &
BGPID=$!
echo "[1] $BGPID"
echo
echo "\$ jobs"
jobs
echo
echo "\$ ps -p $BGPID -o pid,stat,comm"
ps -p $BGPID -o pid,stat,comm 2>&1
echo
echo "\$ kill $BGPID"
kill $BGPID 2>/dev/null
wait $BGPID 2>/dev/null
echo "background job $BGPID terminated"
echo
echo "-- kill <PID> sends SIGTERM(15); kill -9 <PID> sends SIGKILL --"

sec "9. DISK & MEMORY  (df, du, free)"
run "df -h"
run "df -hT | head -5"
run "du -sh /root/cheat"
run "du -h --max-depth=1 /root/cheat"
run "free -h"
run "free -m"

sec "10. ARCHIVES & COMPRESSION  (tar, gzip, zip)"
run "tar -czvf project.tar.gz project"
run "ls -lh project.tar.gz"
run "tar -tzf project.tar.gz"
run "mkdir extracted && tar -xzf project.tar.gz -C extracted && find extracted"
run "gzip -k numbers.txt && ls -l numbers.txt*"
run "gunzip numbers.txt.gz && ls -l numbers.txt"

sec "11. I/O REDIRECTION & PIPES"
run "echo 'written with >' > out.txt && cat out.txt"
run "echo 'appended with >>' >> out.txt && cat out.txt"
run "ls /nonexistent 2> err.txt; cat err.txt"
run "ls /nonexistent > all.txt 2>&1; cat all.txt"
run "ls /etc | wc -l"
run "cat /etc/passwd | grep root | cut -d: -f1"
run "echo 'to stdout and to file' | tee tee.txt"
run "cat tee.txt"

sec "12. NETWORKING BASICS"
run "ip addr show | head -12"
run "ip route"
run "hostname -I"
run "ss -tuln | head -8"
run "ping -c 3 127.0.0.1"
run "curl -sI http://localhost | head -5"

sec "13. USERS, GROUPS, SUDO"
run "id testuser"
run "groups testuser"
run "getent passwd | tail -3"
run "cat /etc/group | tail -5"
run "last 2>/dev/null | head -3 || echo 'no wtmp in container'"

sec "14. SERVICES  (systemctl)"
run "systemctl status nginx --no-pager | head -6"
run "systemctl is-active nginx"
run "systemctl is-enabled nginx"
run "systemctl list-units --type=service --state=running --no-pager | head -10"

sec "15. PACKAGE MANAGEMENT  (apt)"
run "apt list --installed 2>/dev/null | head -6"
run "dpkg -l | head -8"
run "apt-cache policy nginx | head -5"
echo "-- apt update / apt install <pkg> / apt remove <pkg> / apt search <pkg> --"

sec "16. HISTORY, ALIASES, ENV, HELP"
run "echo \$HOME \$USER \$SHELL"
run "env | sort | head -8"
run "export MY_VAR='devops' && echo \$MY_VAR"
run "alias ll='ls -la' && alias | head -3"
run "man ls 2>/dev/null | col -b | head -8"
run "ls --help | head -5"
run "history 2>/dev/null | tail -3 || echo 'history is interactive-shell only'"
