#!/bin/bash
# Task 3: journalctl -- live transcript
run() { echo "\$ $*"; eval "$@" 2>&1; echo; }

echo "###############################################"
echo "# STEP 0: What is journalctl?"
echo "###############################################"
run "systemctl --version | head -1"
run "systemctl status systemd-journald --no-pager | head -12"
echo "--- The journal is a BINARY log database written by systemd-journald. ---"
echo "--- journalctl is the tool used to QUERY it.  Files live here: ---"
run "ls -la /var/log/journal/ 2>/dev/null || ls -la /run/log/journal/"

echo "###############################################"
echo "# STEP 1: View ALL logs (newest at the bottom)"
echo "###############################################"
run "journalctl --no-pager | head -20"

echo "###############################################"
echo "# STEP 2: Most useful flags"
echo "###############################################"
echo "--- -n N : last N lines ---"
run "journalctl -n 10 --no-pager"
echo "--- -r : reverse (newest first) ---"
run "journalctl -r -n 5 --no-pager"
echo "--- -e : jump to the end   |   -f : follow live (like tail -f) ---"
echo "--- -x : add explanatory help text to messages ---"
run "journalctl -xn 5 --no-pager"

echo "###############################################"
echo "# STEP 3: Logs for a SPECIFIC SERVICE  (-u)"
echo "###############################################"
run "systemctl start nginx"
run "systemctl status nginx --no-pager | head -12"
echo "--- THE key command: journalctl -u <service> ---"
run "journalctl -u nginx --no-pager"
echo "--- restart the service and watch new entries appear ---"
run "systemctl restart nginx"
run "journalctl -u nginx --no-pager -n 15"

echo "###############################################"
echo "# STEP 4: Filter by TIME"
echo "###############################################"
run "journalctl --since '10 minutes ago' --no-pager | tail -8"
run "journalctl --since today --no-pager | wc -l"
run "journalctl --since '2026-01-01' --until 'now' --no-pager | wc -l"
echo "--- also accepts: yesterday, '1 hour ago', '2026-09-03 04:00:00' ---"

echo "###############################################"
echo "# STEP 5: Filter by PRIORITY  (-p)"
echo "###############################################"
echo "levels: 0 emerg  1 alert  2 crit  3 err  4 warning  5 notice  6 info  7 debug"
run "journalctl -p err --no-pager -n 10"
run "journalctl -p warning..err --no-pager -n 10"

echo "###############################################"
echo "# STEP 6: Filter by BOOT, by PID, by USER, by EXECUTABLE"
echo "###############################################"
run "journalctl --list-boots --no-pager"
run "journalctl -b --no-pager | head -5"
echo "--- -b -1 would show the PREVIOUS boot ---"
run "journalctl _PID=1 --no-pager -n 5"
run "journalctl /usr/sbin/nginx --no-pager -n 5"
run "journalctl -u nginx -o json-pretty --no-pager -n 1"

echo "###############################################"
echo "# STEP 7: Output formats  (-o)"
echo "###############################################"
run "journalctl -u nginx -o short --no-pager -n 2"
run "journalctl -u nginx -o cat --no-pager -n 3"
run "journalctl -u nginx -o verbose --no-pager -n 1"

echo "###############################################"
echo "# STEP 8: Kernel messages, and writing your own entry"
echo "###############################################"
run "journalctl -k --no-pager -n 5"
run "logger -t devops-homework -p user.notice 'Hello from the DevOps homework, written via logger'"
run "journalctl -t devops-homework --no-pager"

echo "###############################################"
echo "# STEP 9: Disk usage and log rotation / cleanup"
echo "###############################################"
run "journalctl --disk-usage"
run "journalctl --verify 2>&1 | tail -3"
echo "--- cleanup commands (destructive, shown here for reference): ---"
echo "    journalctl --vacuum-size=100M    # keep at most 100 MB"
echo "    journalctl --vacuum-time=7d      # keep only the last 7 days"
echo "    journalctl --rotate              # force rotation right now"
run "journalctl --vacuum-time=2d"
