#!/bin/bash
# Task 1: Soft link vs Hard link -- live transcript
run() { echo "\$ $*"; eval "$@" 2>&1; echo; }

rm -rf /root/linklab; mkdir -p /root/linklab; cd /root/linklab

echo "###############################################"
echo "# STEP 1: Create an original file"
echo "###############################################"
run "echo 'Hello from the original file' > original.txt"
run "cat original.txt"
run "ls -li original.txt"

echo "###############################################"
echo "# STEP 2: Create a HARD link  (ln src link)"
echo "###############################################"
run "ln original.txt hardlink.txt"
run "ls -li original.txt hardlink.txt"

echo "###############################################"
echo "# STEP 3: Create a SOFT/SYMBOLIC link  (ln -s src link)"
echo "###############################################"
run "ln -s original.txt softlink.txt"
run "ls -li original.txt hardlink.txt softlink.txt"

echo "###############################################"
echo "# STEP 4: Compare inode numbers and link counts"
echo "###############################################"
run "stat original.txt"
run "stat hardlink.txt"
run "stat softlink.txt"

echo "###############################################"
echo "# STEP 5: Both links read the same content"
echo "###############################################"
run "cat hardlink.txt"
run "cat softlink.txt"

echo "###############################################"
echo "# STEP 6: Edit through the hard link -> all see it"
echo "###############################################"
run "echo 'Line added through the HARD link' >> hardlink.txt"
run "cat original.txt"
run "cat softlink.txt"

echo "###############################################"
echo "# STEP 7: THE KEY TEST -- delete the original file"
echo "###############################################"
run "rm original.txt"
run "ls -li"
echo "--- Hard link still works (data survives, link count 2 -> 1): ---"
run "cat hardlink.txt"
echo "--- Soft link is now BROKEN / dangling (points to a name that is gone): ---"
run "cat softlink.txt"
run "ls -l softlink.txt"
run "readlink softlink.txt"
run "test -e softlink.txt && echo 'target exists' || echo 'BROKEN LINK: target does not exist'"
run "file softlink.txt"

echo "###############################################"
echo "# STEP 8: Restore the name -> soft link heals itself"
echo "###############################################"
run "ln hardlink.txt original.txt"
run "cat softlink.txt"

echo "###############################################"
echo "# STEP 9: Hard links CANNOT cross filesystems or link directories"
echo "###############################################"
run "mkdir mydir"
run "ln mydir dirhardlink"
echo "--- but a SOFT link to a directory is perfectly legal: ---"
run "ln -s mydir dirsoftlink"
run "ls -l dirsoftlink"
run "ls -ld dirsoftlink/"

echo "###############################################"
echo "# STEP 10: Deleting links"
echo "###############################################"
run "ls -li"
echo "--- Remove a soft link with rm / unlink (NOT rm on the trailing slash) ---"
run "rm softlink.txt"
run "unlink dirsoftlink"
echo "--- Remove a hard link: just rm it; data dies only when link count hits 0 ---"
run "ls -li"
run "rm hardlink.txt"
run "ls -li"
run "cat original.txt"
echo "--- Now delete the LAST hard link: the data is finally freed ---"
run "rm original.txt"
run "ls -li"

echo "###############################################"
echo "# STEP 11: find broken symlinks / count hard links"
echo "###############################################"
run "echo data > f1.txt; ln f1.txt f2.txt; ln f1.txt f3.txt"
run "ls -li f1.txt f2.txt f3.txt"
run "stat -c '%n has %h hard links (inode %i)' f1.txt"
run "find . -type l -xtype l"
run "ln -s /no/such/file broken.link"
echo "--- find dangling symlinks: ---"
run "find . -xtype l"
