apiVersion: v1
kind: Namespace
metadata:
  name: hw16
  labels:
    # Pod Security Admission: reject any pod in this namespace that is not "restricted"-compliant
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
